web/router.ex
defmodule ElixirResources.Router do
  use ElixirResources.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :assign_current_user
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    
    
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_layout do
    plug :put_layout, {ElixirResources.LayoutView, :dashboard}
    plug ElixirResources.AuthenticateAdmin
  end

  scope "/", ElixirResources do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    
  end

  scope "/admin", ElixirResources do
    pipe_through [:browser, :admin_layout]

    resources "/learnings", LearningController
    resources "/postandtalks", PostAndTalkController
    resources "/frameworks", FrameworkController
    resources "/follow", FollowController
    resources "/communities", CommunityController
    resources "/jobs", JobController
    resources "/companies", CompanyController
    resources "/applications", ApplicationController
    resources "/newsletters", NewsletterController
    get "/dashboard", LearningController, :index
  end

  scope "/", as: :admin do
    pipe_through :browser

    get "/admin", ElixirResources.AuthController, :index
    get "/auth/:provider", ElixirResources.AuthController, :request
    get "/auth/:provider/callback", ElixirResources.AuthController, :callback
    delete "/auth/logout", ElixirResources.AuthController, :delete
  end


  defp assign_current_user(conn, _) do
    current_user = get_session(conn, :current_user)
    assign(conn, :current_user, current_user)
  end


  # Other scopes may use custom stacks.
  # scope "/api", ElixirResources do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule ElixirResources.LayoutView do
  use ElixirResources.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ElixirResources!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @current_user do %>
              <li><%= link "Log Out", to: admin_auth_path(@conn, :delete), method: :delete, class: "btn btn-danger" %></li>
            <% else %>
              <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/dashboard.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ElixirResources!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Everything Elixir</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/admin/dashboard">Admin Panel</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="<%= learning_path(@conn, :index) %>"> Learning <span class="sr-only">(current)</span></a></li>
            <li><a href="<%= post_and_talk_path(@conn, :index) %>">Post & Talks</a></li>
            <li><a href="<%= framework_path(@conn, :index) %>">Frameworks</a></li>
            <li><a href="<%= follow_path(@conn, :index) %>">Follow</a></li>
            <li><a href="<%= community_path(@conn, :index) %>">Community</a></li>
            <li><a href="<%= job_path(@conn, :index) %>">Jobs</a></li>
            <li><a href="<%= company_path(@conn, :index) %>">Companies</a></li>
            <li><a href="<%= application_path(@conn, :index) %>">Applications</a></li>
            <li><%= link "Newsletter", to: newsletter_path(@conn, :index) %></li>
          </ul>
        </div>
        <div class="col-sm-9 col-md-10 main">
          <h1 class="page-header">Dashboard</h1>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main>
        </div> 
      </div>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>